<!DOCTYPE html>
<#import "/spring.ftl" as spring />
<html>
<head>
<meta charset="ISO-8859-1">
<title>Booking</title>
</head>
<body>

	<form method="post">
		<label for="customerName">Your name:</label> <input type="text"
			name="customerName" id="customerName"
			placeholdere="What is your name?"> <br>
		<label for="date">Date of appointment:</label> <input type="text"
			name="customerName" id="customerName"
			placeholdere="What is your name?"> <br>
	

	</form>
	<button>Save</button>
</body>
</html>